/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * https://support.google.com/a/answer/166852?hl=en
 */
package sendmail;
import java.io.FileInputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.AuthenticationFailedException;
import javax.mail.MessagingException;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author Tri
 */
public class MainForm extends javax.swing.JFrame {

    Properties prop = new Properties();
    static String username;
    static String password;
    static String selectedMailType = "Gmail account";
    static String mContent;
    static String mTitle;
    static int totalPersonSentPmPerDayLimit = 5000;	// so nguoi gui toi da moi lan bat chuong trinh , co the len toi 9900    
    public Timer timer = new Timer();
    int timePeriod = 1000 * 60 * 5 ; // 5p // test default
    JavaEmail javaEmail;
    static String[] recipientBrowseArray;
    public static boolean isBrowseFile = false;
    static boolean isTextFormat = true;
    
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        try {
            checkLicense();
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            initComponents();
            initValue();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        chooseAccCbx = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titleTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        statusLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mailContent = new javax.swing.JEditorPane();
        statusContent = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filePath = new javax.swing.JTextField();
        btnChooseFile = new javax.swing.JButton();
        totalNickLbl = new javax.swing.JLabel();
        rdText = new javax.swing.JRadioButton();
        rdHtml = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoSendEmail");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTabbedPane1.setEnabled(false);

        chooseAccCbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gmail account", "Yahoo account" }));
        chooseAccCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAccCbxActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose email account:");

        jLabel4.setText("Mail title:");

        titleTf.setToolTipText("");

        jLabel5.setText("Mail content:");

        sendBtn.setText("Send");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        statusLbl.setText("Status:");

        jScrollPane1.setViewportView(mailContent);

        statusContent.setText("...");
        statusContent.setMaximumSize(new java.awt.Dimension(50, 14));

        jLabel7.setText("File email list:");

        filePath.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        filePath.setMinimumSize(new java.awt.Dimension(200, 20));

        btnChooseFile.setText("Browse");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        totalNickLbl.setText(" ");

        rdText.setText("Text format");

        rdHtml.setText("HTML format");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(sendBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(statusLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chooseAccCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(totalNickLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnChooseFile)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(titleTf)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdText)
                .addGap(18, 18, 18)
                .addComponent(rdHtml)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseAccCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(totalNickLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(filePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseFile))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(titleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdText)
                    .addComponent(rdHtml))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(statusContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Send Mail", jPanel1);

        jLabel1.setText("Telephone: 0943060969");

        jLabel2.setText("Facebook:");

        jLabel6.setText("<HTML><U>http://www.facebook.com/speedupbiz/notes</U></HTML>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(369, 369, 369))
        );

        jTabbedPane1.addTab("Help", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        
        mTitle = titleTf.getText();
        mContent = mailContent.getText();
        
        if ( mTitle.trim().equals("") || mContent.trim().equals("") ){
            JOptionPane.showMessageDialog(null, "Fill title and content");
            return;
        }
        
        sendBtn.setText("Sending...");
        jProgressBar1.setIndeterminate(true);
        
        JavaEmail.countNumberPersonSentToday = 0;
        statusContent.setText("");
        
        if ( rdHtml.isSelected() ){
            isTextFormat = false;
        }
        
        javaEmail = new JavaEmail();
        javaEmail.setMailServerProperties();
        timer.schedule(new RemindTask1(), 0, timePeriod);
    }//GEN-LAST:event_sendBtnActionPerformed

    private void checkLicense() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date expireDate = sdf.parse("2016-9-30");
            Date today = new Date();

            if (expireDate.before(today)) {
//                JOptionPane.showMessageDialog(this, "License hết hạn. liên hệ: http://www.facebook.com/speedupbiz/ or 090 4710548");
                System.exit(0);
            }
        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    class RemindTask1 extends TimerTask {

        @Override
        public void run() {
            
            if (JavaEmail.totalMemSent >= JavaEmail.recipientArray.length) {	// da gui het danh sach
                statusContent.setText("Sending all email finished!");
                JOptionPane.showMessageDialog(null, "Sending all email finished!");
                
                sendBtn.setText("Send");
                jProgressBar1.setValue(100);
                jProgressBar1.setIndeterminate(false);    
                
                timer.cancel();
                return;
            }

            // setup and send mail
            try {
                javaEmail.sendEmail();
            } catch (AuthenticationFailedException ex){
                statusContent.setText("Sai username, password hoặc chưa thiết lập bảo mật.");
                // https://www.google.com/settings/security/lesssecureapps
                return;
            } catch (MessagingException ex) {
                MyLogger.logger.log(Level.WARNING, "Lỗi chưa thiết lập bảo mật.");
            } catch (Exception ex) {
                MyLogger.logger.log(Level.WARNING, "Error2 không xác định");
            }
        }
    }
    
    private void chooseAccCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseAccCbxActionPerformed
        // TODO add your handling code here:
        selectedMailType = chooseAccCbx.getSelectedItem().toString();
        if ( selectedMailType.equalsIgnoreCase("Yahoo account") ){
            username = prop.getProperty("yahoouser").trim();
            password = prop.getProperty("yahoopass").trim();            
        } else {
            username = prop.getProperty("gmailuser").trim();
            password = prop.getProperty("gmailpass").trim();            
        }
    }//GEN-LAST:event_chooseAccCbxActionPerformed

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        final JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        StringBuilder text = new StringBuilder();
        
        try {
            // Open an input stream
            Scanner reader = new Scanner(fc.getSelectedFile());
            filePath.setText( fc.getSelectedFile().getAbsolutePath() );
            while (reader.hasNextLine()) {
                String line = reader.nextLine();
                text.append(line);
            }
            
            if ( text.toString().contains(",") ){
                recipientBrowseArray = text.toString().split(",");
            } else {
                recipientBrowseArray = text.toString().split(";");
            }
            
            isBrowseFile = true;
            totalNickLbl.setText( "("  + recipientBrowseArray.length + " nicks)" );
            MyLogger.logger.log(Level.INFO, "Total member in browse file: {0}", recipientBrowseArray.length);
        } catch( Exception ex ) {
            MyLogger.logger.log(Level.WARNING, "Error3: {0}", ex);
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void initValue() {
        
        new MyLogger();
        
        // init GUI
        rdText.setSelected(true);
        ButtonGroup group = new ButtonGroup();
        group.add(rdText);
        group.add(rdHtml);
        
        // load config
        prop = new Properties();
        try {        
            prop.load(new FileInputStream("config.txt"));
            username = prop.getProperty("gmailuser").trim();
            password = prop.getProperty("gmailpass").trim();
            String tmp = prop.getProperty("totalPersonPerDay").trim();
            String tmp2 = prop.getProperty("timePerSendMailMin").trim();
            timePeriod = Integer.parseInt(tmp2) * 1000 * 60; // => second => milisecond
            
            if (tmp != null) {
                int num = Integer.parseInt(tmp);
                if (num < totalPersonSentPmPerDayLimit) {
                    totalPersonSentPmPerDayLimit = num;
                }
            }
            
        } catch (IOException ex) {
            MyLogger.logger.log(Level.WARNING, "Can not read config or file is not exist");
        } catch (Exception ex) {
            MyLogger.logger.log(Level.WARNING, "Error1: {0}", ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JComboBox chooseAccCbx;
    private javax.swing.JTextField filePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JEditorPane mailContent;
    private javax.swing.JRadioButton rdHtml;
    private javax.swing.JRadioButton rdText;
    public static javax.swing.JButton sendBtn;
    public static javax.swing.JLabel statusContent;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextField titleTf;
    private javax.swing.JLabel totalNickLbl;
    // End of variables declaration//GEN-END:variables

    
}
